FROM node:22.3.0-alpine
USER root
WORKDIR /app

RUN rm -rf node_modules

#package.jsonのパスを指定してインストールできる
COPY ./fe/package.json /app/package.json
COPY ./fe/package-lock.json /app/package-lock.json
RUN npm install

ENTRYPOINT ["npm", "start"]